#
# This Config file is used to add/remove/edit services on the Homelab Dashboard
#
# Once you are done making changes to this file, save it and refresh the dashboard
#

services:
  proxmox:
    logoPath: '#'
    serviceName: 'Proxmox VE'
    ipv4Address: '192.168.1.200'
    port: '8006'
    hostName: 'pve'
  openmediavault:
    logoPath: '/'
    serviceName: 'Open Media Vault - NAS'
    ipv4Address: '192.168.1.28'
    port: '80'
    hostName: 'nas-omv'
  smc-ipmi:
    logoPath: '/'
    serviceName: 'Supermicro IPMI'
    ipv4Address: '192.168.1.28'
    port: '80'
    hostName: 'SMC-X8SIL-F'
  
template:
  service:
    logoPath: 'path-to-logo-image'
    serviceName: 'name-of-service'     # Name of the service. This text will be displayed as the title of the service in the dashboard
    ipv4Address: 'address-of-service'  # The IPV4 address of the service
    port: 'port-number-for-service'     # The port number used to access the service
    hostName: 'hostname-of-service'     # The host name of the service
